# Generated by Django 6.0.3 on 2026-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diego_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Diego Tomas Dominguez', help_text='Your full name displayed on the homepage.', max_length=100)),
                ('quote', models.CharField(default='The best way to predict the future is to build it.', help_text='Your personal quote or tagline.', max_length=255)),
                ('profile_image', models.ImageField(blank=True, help_text='Upload your profile photo (recommended size: 400x400px).', null=True, upload_to='profile/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one home section can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Section',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_home')],
            },
        ),
    ]
